name: Copy Specified Files from Public Repo

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Public GitHub Repo URL (default is set to Adobe AEM Boilerplate)'
        required: false
        default: 'https://github.com/adobe/aem-block-collection.git'
        type: string

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Clone specified public repo
        run: git clone ${{ github.event.inputs.repo_url }} temp_repo

      - name: Copy specified files
        run: |
          mkdir -p ./blocks/modal
          cp temp_repo/blocks/modal/modal.js ./blocks/modal/modal.js
          cp temp_repo/blocks/modal/modal.css ./blocks/modal/modal.css
          ls -l .
          pwd

      - name: Commit and push the copied files
        run: |
          git status
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add blocks
          git status
          git commit -m "Copy specified files from Adobe AEM Boilerplate"
          git push

