name: Copy Specified Files from Adobe AEM Block Collection

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for authentication
          
      - name: Example step
        run: echo "Secret value is ${{ secrets.GITHUB_TOKEN }}"

      - name: Clone specified public repo
        run: git clone https://github.com/adobe/aem-block-collection.git temp_repo

      - name: Copy specified files
        run: |
          mkdir -p ./blocks/modal
          cp temp_repo/blocks/modal/modal.js ./blocks/modal/modal.js
          cp temp_repo/blocks/modal/modal.css ./blocks/modal/modal.css

      - name: Configure Git
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push the copied files
        run: |
          git add blocks/modal/modal.js blocks/modal/modal.css
          git status
          git commit -m "Copy specified files from Adobe AEM Block Collection" || echo "No changes to commit"
          git push
