name: Copy Files/Folders within Current Repository

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source Repository (format: owner/repo)'
        required: true
      source_path:
        description: 'File/Directory Path to Copy from Source Repo'
        required: true
      source_pat:
        description: 'PAT for Source Repo (if private, leave blank if public)'
        required: false
      pat:
        description: 'PAT for operations, defaults to using GITHUB_TOKEN'
        required: false

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Configuration
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Clone Source Repository
        env:
          SOURCE_PAT: ${{ github.event.inputs.source_pat }}
        run: |
          if [ -z "$SOURCE_PAT" ]; then
            git clone https://github.com/${{ github.event.inputs.source_repo }}.git source_repo
          else
            git clone https://${SOURCE_PAT}@github.com/${{ github.event.inputs.source_repo }}.git source_repo
          fi

      - name: Copy Specified Files/Folders
        run: |
          mkdir -p blocks/accordion
          cp -r source_repo/${{ github.event.inputs.source_path }} ./${{ github.event.inputs.source_path }}
          ls -l

      - name: Configure Git for Current Repository Operations
        env:
          PAT: ${{ github.event.inputs.pat }}
        run: |
          if [ -z "$PAT" ]; then
            echo "here"
            echo "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
            git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          else
            git remote set-url origin https://${PAT}@github.com/${{ github.repository }}.git
          fi

      - name: Commit and Push Changes to Current Repository
        run: |
          git add .
          git commit -m "Copy files/folders from ${{ github.event.inputs.source_repo }}"
          git push
